import Head from 'next/head'
import CustomAppBar from "../components/CustomAppBar"
import CustomCard from '@/components/CustomCard'
import { Box, Grid } from '@mui/material'

const labels = [
  {
    label: 270,
    summary: "hsdkjfhdf jkdhfkjd jkshgfkj"
  },
  {
    label: 276,
    summary: "hsdkjfhdf jkdhfkjd jkshgfkj"
  },
  {
    label: 278,
    summary: "hsdkjfhdf jkdhfkjd jkshgfkj"
  },  
  {
    label: 837,
    summary: "hsdkjfhdf jkdhfkjd jkshgfkj"
  },

]

export default function Home() {
  return (
    <>
      <Head>
        <title>AES</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <h1>Landing Page</h1> */}
        <img alt="image" src="/aeshome.webp"  width="100%" height="350px" style={{objectFit: 'cover'}} />
        <Box sx={{mt: 5}}>
          <Grid container spacing={2}>
            {
              labels.map(({label, summary}) => {
                return <Grid item xs={12} md={3}>
                  <CustomCard label={label} summary={summary} /> 
                </Grid>
              })
            }
          </Grid>
        </Box>


        
      </main>
    </>
  )
}
