import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>AES</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        {/* <h1>Landing Page</h1> */}
        <img alt="image" src="/AES_Home.jpg"  width="100%" height="100%" margin = '0' padding='0' style={{objectFit: 'cover'}} />        
      </main>
    </>
  )
}
